### ISSUE TITLE
Perks

### ISSUE THREAD

**Issue by hg2022YIPPY** [Lurkars/gloomhavensecretary#21]
Now we are not able to select perks normally, we have to triple click before a mark will should up. Example If you set the level to 9, we have to triple click to get the mark to show up.

**Comment by hg2022YIPPY** [comment]
It's working great now.

**Comment by Lurkars** [comment]
I didn't change anything, but I think it's just a out my lack of documentation about alll features and how it works.

The change of character perks is disabled during a scenario (besides the double click fallback), because changing perks would automatically shuffle AM deck and is just not possible during scenario as in physical game. So if you're already started round, it's just disabled. So you must set new scenario and don't start round or finish scenario beforehand.
