### ISSUE TITLE
Suggestion: multi-column mode

### ISSUE THREAD

**Issue by smingerson** [Lurkars/gloomhavensecretary#5]
Thank you for providing such a great tool for the Gloomhaven community!

One thing that I think would improve usability in some cases is providing an option to change from a scrolling list of entities to multiple columns of entities (perhaps scrolling would still be needed depending on number of entities). This would allow viewing more/all of the turns in a round at once, making planning during the round easier. Apologies if I missed a similar option, I just only recently started using the app.

Below is a low-quality example. I've formatted it as go down the first column, then down the second, but have no preference between that and working left-to-right, top-to-bottom.

![image](https://user-images.githubusercontent.com/31328867/177393916-9568c16a-0bf8-481b-a7ac-60674b59e4d4.png)

**Comment by Lurkars** [comment]
Yes I have this of course in mind. But tried to do it a while ago and it seems more complicated than I thought, because it must be very flexible.

It would be easy in a 
| 1 | 2 |
| --- | --- | 
| 3 | 4 |
| 5 | 6 |

format. But with 

| 1 | 4 |
| --- | --- | 
| 2 | 5 |
| 3 | 6 |

wrapping is complicated. Maybe I find a solution later, but focusing now more on getting feature complete and adding all data. But I'll keep this open. This is definitely something for fine tuning the app!

**Comment by Lurkars** [comment]
First 2 column version added with https://github.com/Lurkars/gloomhavensecretary/commit/5d8d3ff80abcc7ed53d2dc59f094d8c359164c8e 
if zoomed out and figures stack, 2 columns should be shown. It added a small flickering effect when figures added/removed, because of calculation. So I think there is many room for improvement, but basic implementation is done.
