### ISSUE TITLE
Automatic expire conditions not working in characters or monster

### ISSUE THREAD

**Issue by backbeat99** [Lurkars/gloomhavensecretary#8]
Maybe I'm doing something wrong or the feature it's disabled right now , but I tried with Immobilize , Stun , etc with this setting (Automatic expire conditions)  enabled and don't seem to work . 
After the round it's over the icons conditions stills reflects in the board of each character/monster.
I'm using version 0.9.6 and server 0.9.5

**Comment by Lurkars** [comment]
Maybe I need some more details. But they should be removed after TURN. So if entities already made their turn, conditions stay until next turn. A turn is done by clicking through the entities images, so a entity made it's turn when it's grayed out. If you click on "Next Round" before all turns finished (the last will always be finished), you'll be asked if you want to "Confirm", then the round is just ended without all turns, or the option "Confirm and end all turns", then all turns are also made and conditions expired. I may do a short screen recording for you, if it helps. Otherwise, please provide more infos what you are exactly doing and expecting. (I assume in menu under sttings "Automatic expire conditions" is checked!?)

**Comment by Lurkars** [comment]
Ah okay, I notice a bug on testing: when I just "Confirm" round and not end properly, on next turn expiring is not working anymore!

**Comment by Lurkars** [comment]
should be fixed with https://github.com/Lurkars/gloomhavensecretary/commit/b460315c02b678a38f4669513cd466a349958ce1 (v0.9.7)
